source "http://rubygems.org"

gem "rest-client"

gem "bson_ext"
gem "yajl-ruby"
gem "nokogiri"

group :vcap do
  gem "vcap_logging", "= 0.1.4"
  gem "cf-uaac", "= 1.3.3"
  gem "cfoundry", :github => "cloudfoundry/vmc-lib", :submodules => true

  git "git://github.com/cloudfoundry/vmc-plugins.git" do
    gem "tunnel-vmc-plugin"
    gem "console-vmc-plugin"
  end
end
