source "http://rubygems.org"

gem "rest-client"

gem "bson_ext"
gem "yajl-ruby"
gem "nokogiri"

group :vcap do
  gem "vcap_logging", "= 0.1.4"
  gem "cf-uaac", "= 1.3.3"
  gem "cfoundry", :git => "git://github.com/cloudfoundry/vmc-lib.git", :submodules => true
end
